name: check

on:
  schedule:
  - cron: "0 */12 * * *"

jobs:
  new-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT }}
    - name: get-latest-version
      run: |
        VERSION="$(wget 2>/dev/null https://github.com/notepad-plus-plus/notepad-plus-plus/releases -qSO- | grep -Eo ".*.x6" | head -1 | grep -Po "(\d+\.)+\d+")"
        VERSION_CHECK="$(echo $VERSION | wc -l)"
        last=$(tail -n1 .build | awk '{print $4}')
        if [ "$VERSION_CHECK" -eq 1 ]; then
         if [ "$last" != "$VERSION" ]; then
           echo "$(date -u --rfc-3339=seconds) Version $VERSION" >> .build
         fi
        else
         echo "No update released." 
        fi
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Trigger build for new version
        branch: master